version: '3.5'

services:
  db:
    image: postgres:14.18
    container_name: db
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_PASSWORD=0000
      - POSTGRES_USER=lipton
      