# Generated by Django 5.2.4 on 2025-07-03 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 3, 18, 26, 37, 703664, tzinfo=datetime.timezone.utc)),
        ),
    ]
