# Generated by Django 5.2.4 on 2025-07-09 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='content',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 9, 10, 40, 29, 84135, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='operation',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
