# Generated by Django 5.2.4 on 2025-07-04 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_operation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('IN', 'Доход'), ('EX', 'Расход')], default='IN'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 7, 18, 28, 483093, tzinfo=datetime.timezone.utc)),
        ),
    ]
