# Generated by Django 5.2.4 on 2025-07-09 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_operation_content_alter_operation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 9, 10, 45, 6, 574550, tzinfo=datetime.timezone.utc)),
        ),
    ]
