# Generated by Django 5.2.4 on 2025-07-10 09:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_operation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='name',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 10, 9, 43, 53, 553529, tzinfo=datetime.timezone.utc)),
        ),
    ]
