# Generated by Django 5.2.4 on 2025-07-04 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_category_type_alter_operation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('IN', 'Доход'), ('EX', 'Расход')], default='EX'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 4, 10, 27, 2, 609943, tzinfo=datetime.timezone.utc)),
        ),
    ]
