# Generated by Django 5.2.4 on 2025-07-11 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_operation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 11, 19, 14, 44, 197718, tzinfo=datetime.timezone.utc)),
        ),
    ]
